title: TaskValve
description: TaskValve Documentation
theme: just-the-docs

url: https://taskvalve.github.io/documentation

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/taskvalve/documentation

color_scheme: custom

footer_content: "Copyright &copy; 2023 TaskValve."
